# Site settings
title: Portfolio
subtitle: Analise de dados
email: diogo.lima@ccc.ufcg.edu.br
description: > # this means to ignore newlines until "baseurl:"
  portfólio das tarefas realizadas na disciplina de análise de dados
baseurl: "/portifolioAnaliseDeDados" # the subpath of your site, e.g. /blog/
url: "https://diogoflorencio.github.io/portifolioAnaliseDeDados/" # the base hostname & protocol for your site
github_username:  diogoflorencio
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
